name: ci-java-workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn package 
    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test