name: ci-java-workflow
on:
  pull_request:
      branches:
        - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17','21']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn package 
    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test